In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
corpus = [
    '我 爱 北京 天安门',
    '北京 欢迎 您',
    '欢迎 到 北京 来',
    '同一个 世界 同一个 梦想'
]
# 初始化CountVectorizer
vectorizer = CountVectorizer()

训练语料，返回文档-特征词-词频矩阵

In [6]:
X = vectorizer.fit_transform(corpus)
X

<4x6 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [7]:
print(type(X))

<class 'scipy.sparse.csr.csr_matrix'>


get_feature_names()：以列表形式返回特征词

In [9]:
print(vectorizer.get_feature_names())

['世界', '北京', '同一个', '天安门', '梦想', '欢迎']


vocabulary_：以字典形式返回特征词：列表索引位置，不是特征词：词频字典！！！

In [23]:
print(vectorizer.vocabulary_)

{'北京': 1, '天安门': 3, '欢迎': 5, '同一个': 2, '世界': 0, '梦想': 4}


In [8]:
# 矩阵形式
print(X.toarray())

[[0 1 0 1 0 0]
 [0 1 0 0 0 1]
 [0 1 0 0 0 1]
 [1 0 2 0 1 0]]


根据学习到的特征模型去预测新的语料文本：

In [120]:
new_corpus = [
    '北京 天安门 夜景 北京',
    '天安门 北京 夜景 湖南 长沙'
]
print(vectorizer.transform(new_corpus))

  (0, 1)	2
  (0, 3)	1
  (1, 1)	1
  (1, 3)	1
