# 非负矩阵分解(NMF)

非负矩阵分解(non-negative matrix factorization，以下简称NMF)是一种非常常用的矩阵分解方法，它可以适用于很多领域，比如图像特征识别，语音识别等。

[sklearn](http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.NMF.html)

[文本主题模型之非负矩阵分解(NMF)](https://www.cnblogs.com/pinard/p/6812011.html)

In [1]:
import numpy as np
X = np.array([[1,1,5,2,3], [0,6,2,1,1], [3, 4,0,3,1], [4, 1,5,6,3]])
from sklearn.decomposition import NMF
model = NMF(n_components=2, alpha=0.01)

In [3]:
W = model.fit_transform(X)
H = model.components_
print(X)
print(W)
print(H)

[[1 1 5 2 3]
 [0 6 2 1 1]
 [3 4 0 3 1]
 [4 1 5 6 3]]
[[ 1.67371185  0.02013017]
 [ 0.40564826  2.17004352]
 [ 0.77627836  1.5179425 ]
 [ 2.66991709  0.00940262]]
[[ 1.32014421  0.40901559  2.10322743  1.99087019  1.29852389]
 [ 0.25859086  2.59911791  0.00488947  0.37089193  0.14622829]]
